#! /bin/sh 

$HOME/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
picom --config $HOME/.config/picom/picom.conf &
setxkbmap us &
nitrogen --restore &
pgrep -x sxhkd > /dev/null || sxhkd &
bspwm &
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        6
bspc config window_gap          35

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#f6c177"
bspc config normal_border_color "#9ccfd8"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

